# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20160416_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
