# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_auto_20160416_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='name',
        ),
    ]
