# Generated by Django 2.1.1 on 2018-09-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20180909_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_caption',
            field=models.CharField(default='A default caption for all images', max_length=240),
            preserve_default=False,
        ),
    ]
