# Generated by Django 2.1.1 on 2018-09-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_image_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='height_field',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_caption',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='width_field',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
