# Generated by Django 2.1.1 on 2018-10-05 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20181005_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='summary',
            new_name='briefing',
        ),
    ]
