# Generated by Django 2.1.1 on 2018-11-07 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20181107_0814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contributor',
            new_name='author',
        ),
    ]
